- name: Gather facts about the {{ role_type }} RDS Subnets in {{ env }}
  ec2_vpc_subnet_facts:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    filters:
      "tag:Environment": "{{ env }}"
      "tag:Application": "{{ role_type }}"
      "tag:Tier": rds
  register: rds_subnets

- debug:
    var: rds_subnets
    verbosity: 2

- debug:
    var: rds_db_instances
    verbosity: 2

- include_tasks: launch_rds_instance.yml
  with_items: "{{ rds_db_instances }}"
  loop_control:
    loop_var: rds_item
