- name: Remove the {{ role_type }}-{{ db_instance_type }} RDS instance
  rds_instance:
    region: "{{ region }}"
    profile: "{{ aws_account_name }}"
    instance_name: "{{ item.value.db_instance_identifier }}"
    wait: "{{ item.value.wait }}"
    wait_timeout: "{{ item.value.wait_timeout }}"
    state: absent
  with_dict: "{{ rds.db_instances }}"
  when: "db_instance_type  == 'master'"
