- name: Get the hosted zone infor
  route53_facts:
    dns_name: "{{ tld_name_internal }}"
    query: hosted_zone
    hosted_zone_method: list_by_name
    profile: "{{ profile|default(omit) }}"
  register: hosted_zone_out

- set_fact:
    hosted_zone_id: "{{ hosted_zone_out.HostedZones.0.Id.split('/')[2] }}"

- include_tasks: destroy_rds_instance.yml
  with_items: "{{ rds_db_instances }}"
  loop_control:
    loop_var: rds_item
